# Generated by Django 6.0.5 on 2026-05-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('grade', models.CharField(max_length=5)),
                ('size', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('maker', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True, default='')),
                ('is_manual', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5, unique=True)),
                ('price_coded', models.IntegerField(default=0)),
                ('price_noncode', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=5)),
                ('size', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('maker', models.CharField(max_length=50)),
                ('price_coded', models.IntegerField()),
                ('price_noncode', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('tech', 'Technician')], default='tech', max_length=10)),
            ],
        ),
    ]
