# Generated by Django 6.0.5 on 2026-05-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chip',
            name='status',
            field=models.CharField(choices=[('coded', 'Coded'), ('noncode', 'Non-Coded')], default='coded', max_length=15),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='status',
            field=models.CharField(default='coded', max_length=15),
        ),
    ]
