# Generated by Django 6.0.5 on 2026-05-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_chip_status_scanhistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chip',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chip',
            name='alternate_codes',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='chip',
            name='ocr_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
