# Generated by Django 6.0.5 on 2026-06-07 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_chip_alias_chip_alternate_codes_chip_ocr_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scans/'),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='matched_chip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner.chip'),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='ocr_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='scan_status',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
    ]
