# Generated by Django 6.0.5 on 2026-06-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_scanhistory_image_scanhistory_matched_chip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonCodePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, unique=True)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
