# Generated by Django 6.0.5 on 2026-06-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_noncodeprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='chip',
            name='image_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='chip',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='chips/'),
        ),
    ]
