# Generated by Django 6.0.5 on 2026-06-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_chip_image_hash_chip_reference_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chip',
            name='image_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
