# Generated by Django 6.0.5 on 2026-06-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_chip_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chip',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='chip',
            name='image_path',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='code',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
