# Generated by Django 6.0.5 on 2026-06-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0009_approvalrequest_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='noncodeprice',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('tech', 'Technician')], default='tech', max_length=10),
        ),
        migrations.AddField(
            model_name='price',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('tech', 'Technician')], default='tech', max_length=10),
        ),
        migrations.AlterField(
            model_name='noncodeprice',
            name='size',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='grade',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='noncodeprice',
            unique_together={('size', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('grade', 'role')},
        ),
    ]
